export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const GET_PLACES_FAIL = "GET_PLACES_FAIL";
export const ASSIGN_STUDENT_SUCCESS = "ASSIGN_STUDENT_SUCCESS";
export const ASSIGN_STUDENT_FAIL = "ASSIGN_STUDENT_FAIL";
