# Generated by Django 5.0.7 on 2024-11-16 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=50, unique=True)),
                ('career_secretary_name', models.CharField(max_length=50, unique=True)),
                ('duration_years', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_field_intitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitution_name', models.CharField(max_length=50)),
                ('institution_branch_name', models.CharField(max_length=50, null=True)),
                ('clinic_field_code', models.CharField(max_length=50)),
                ('clinic_field_address', models.CharField(max_length=50)),
                ('clinic_field_rut', models.CharField(max_length=50)),
                ('clinic_field_razon_social', models.CharField(max_length=50)),
                ('is_clinic_field_agreement_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=50)),
                ('university_rut', models.CharField(max_length=50)),
                ('campus_name', models.CharField(max_length=50)),
                ('campus_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_field_unity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_field_unity_name', models.CharField(max_length=50)),
                ('clinic_field_intitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.clinic_field_intitution')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField()),
                ('career_year', models.PositiveIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.career')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('emergency_name', models.CharField(max_length=50)),
                ('emergency_number', models.CharField(max_length=15)),
                ('student_address', models.CharField(max_length=100)),
                ('observation', models.TextField(max_length=500)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.career')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.semester')),
            ],
            options={
                'unique_together': {('rut', 'career')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
                ('nrc', models.CharField(max_length=50)),
                ('type_of_internship', models.CharField(choices=[('curricular', 'Curricular'), ('internado', 'Internado')], default=None, max_length=30)),
                ('total_required_hours', models.FloatField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_field_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('is_student_attended', models.BooleanField(default=None, null=True)),
                ('is_place_available', models.BooleanField(default=None, null=True)),
                ('observation', models.CharField(max_length=50)),
                ('clinic_field_unity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.clinic_field_unity')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='campoclinico.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.subject')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campoclinico.university'),
        ),
    ]
