export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS'
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL'
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS'
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL'

// Careers
export const GET_CAREERS_SUCCESS = 'GET_CAREERS_SUCCESS';
export const GET_CAREERS_FAIL = 'GET_CAREERS_FAIL';

// Semesters
export const GET_SEMESTERS_SUCCESS = 'GET_SEMESTERS_SUCCESS';
export const GET_SEMESTERS_FAIL = 'GET_SEMESTERS_FAIL';